name: Call C# PullTwitterOpen API

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Allows to trigger it manually from the GitHub UI

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call PullTwitterOpen API
        run: |
          curl --fail --show-error --silent -X GET "https://anchor-press-api.azurewebsites.net/api/Schedular/PullTwitterOpen"
