name: Call C# PullTwitterOpen API

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X GET "https://anchor-press-api.azurewebsites.net/api/Schedular/PullTwitterOpen"
