name: Call C# SendTweetReplyOpen API Randomly

on:
  schedule:
    # Runs every 3 minutes; the actual call will happen randomly in that run
    - cron: "*/15 * * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Random Delay (15 to 20 mins)
        id: random-delay
        run: |
          RANDOM_DELAY=$((RANDOM % (20*60 - 15*60 + 1) + 3*60))
          echo "Random delay: $RANDOM_DELAY seconds"
          echo "delay=$RANDOM_DELAY" >> $GITHUB_OUTPUT

      - name: Sleep for Random Delay
        run: |
          echo "Sleeping for ${{ steps.random-delay.outputs.delay }} seconds..."
          sleep ${{ steps.random-delay.outputs.delay }}

      - name: Call API
        run: |
          curl -X GET "https://anchor-press-api.azurewebsites.net/api/Twitter/SendTweetReplyOpen"
