name: Call C# SendTweetReplyOpen API Randomly
on:
  schedule:
    # Runs every 20 minutes
    - cron: "*/20 * * * *"
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  call-api:
    #concurrency:
      #group: send-tweet-reply-open
      #cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Generate Random Delay (15 to 20 mins)
        id: random-delay
        shell: bash
        run: |
          MIN=900    # 15 * 60
          MAX=1200   # 20 * 60
          RANDOM_DELAY=$((RANDOM % (MAX - MIN + 1) + MIN))
          echo "Random delay: $RANDOM_DELAY seconds"
          echo "delay=$RANDOM_DELAY" >> $GITHUB_OUTPUT

      - name: Sleep for Random Delay
        run: |
          echo "Sleeping for ${{ steps.random-delay.outputs.delay }} seconds..."
          sleep ${{ steps.random-delay.outputs.delay }}

      - name: Call API with Error Handling
        id: api-call
        run: |
          echo "Calling SendTweetReplyOpen API..."
          
          # Make API call and capture response
          RESPONSE=$(curl -w "\nHTTP_STATUS:%{http_code}" \
            -X GET https://anchor-press-api.azurewebsites.net/api/Schedular/SendTweetReplyOpen \
            -H "X-API-KEY: ${{ secrets.SCHEDULER_SECRET_KEY }}" \
            -H "Accept: application/json" \
            2>&1) || API_CALL_FAILED=true
          
          # Extract HTTP status code and response body
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS:" | cut -d: -f2)
          RESPONSE_BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS:/d')
          
          echo "HTTP Status: $HTTP_STATUS"
          echo "Response Body: $RESPONSE_BODY"
          
          # Check if API call failed or returned error status
          if [ "$API_CALL_FAILED" = true ]; then
            echo "API call failed completely (network/connection error)"
            echo "Error details: $RESPONSE_BODY"
            exit 1
          elif [ "$HTTP_STATUS" = "400" ]; then
            echo "API returned BadRequest (400) - Exception occurred in SendTweetReply service"
            echo "Exception message: $RESPONSE_BODY"
            exit 1
          elif [ "$HTTP_STATUS" -ge 400 ]; then
            echo "API returned error status: $HTTP_STATUS"
            echo "Error response: $RESPONSE_BODY"
            exit 1
          else
            echo "API call successful (Status: $HTTP_STATUS)"
            echo "Tweet reply sent successfully!"
            if [ -n "$RESPONSE_BODY" ]; then
              echo "Response: $RESPONSE_BODY"
            fi
          fi

      - name: Handle Failure
        if: failure()
        run: |
          echo "Workflow failed!"
          echo "The API call encountered an error. Check the logs above for details."
          echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
