name: Call C# SendTweetReplyOpen API Randomly

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/20 * * * *"
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  call-api:
    #concurrency:
      #group: send-tweet-reply-open
      #cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Generate Random Delay (15 to 20 mins)
        id: random-delay
        shell: bash
        run: |
          MIN=900    # 15 * 60
          MAX=1200   # 20 * 60
          RANDOM_DELAY=$((RANDOM % (MAX - MIN + 1) + MIN))
          echo "Random delay: $RANDOM_DELAY seconds"
          echo "delay=$RANDOM_DELAY" >> $GITHUB_OUTPUT

      - name: Sleep for Random Delay
        run: |
          echo "Sleeping for ${{ steps.random-delay.outputs.delay }} seconds..."
          sleep ${{ steps.random-delay.outputs.delay }}

      - name: Call API
        run: |
          curl --fail --show-error --silent -X GET https://anchor-press-api.azurewebsites.net/api/Schedular/SendTweetReplyOpen \
          -H "X-API-KEY: ${{ secrets.SCHEDULER_SECRET_KEY }}"
